language: php

matrix:
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3
    env: PHPSTAN=1

script:
    - if [[ $PHPSTAN == "1" ]]; then
        composer require --dev phpstan/phpstan-nette:^0.11 &&
        vendor/bin/phpstan analyse src --configuration=.phpstan/phpstan.neon;
      fi

before_script:
  - composer self-update
  - composer install
